meta_product_name: "Excuse Engine"
meta_title: "Excuse Engine - Putting the Pro in Procrastinators"
meta_description: "Specialists in location-based excuses"
meta_image: "excuseteam.jpg" # should exist in `app/assets/images/`
twitter_account: "@EngineExcuse"   # required for Twitter Cards
